In [39]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import date, datetime

### Datos

In [40]:
sales = pd.read_csv('../data/sales.csv')
display(sales)

,id,doc_id,sale_date,total_cost,net_price,gross_price,profit,quantity,customer_id,product_id,product_class_id,route_id,warehouse_id
0,761095,gdl 455104,2025-04-30,"1,034.76","2,304.62","2,304.62","1,269.86",10,14058,SAL2,nat,2.00,gdl
1,761096,gdl 455104,2025-04-30,"3,349.56","5,965.76","5,965.76","2,616.20",5,14058,SAL30,nat,2.00,gdl
2,761097,gdl 455104,2025-04-30,"3,366.43","5,916.17","5,916.17","2,549.73",6,14058,SBP18,nat,2.00,gdl
3,761098,gdl 455104,2025-04-30,"1,334.00",0.00,0.00,"-1,334.00",6,14058,SBP6,nat,2.00,gdl
4,761099,gdl 453004,2025-04-01,452.73,799.32,799.32,346.60,1,14060,8+18,nat,26.00,gdl
...,...,...,...,...,...,...,...,...,...,...,...,...,...
708012,761090,gdl 455104,2025-04-30,750.96,"1,336.10","1,336.10",585.13,2,14058,PREM20,dmd,2.00,gdl
708013,761091,gdl 455104,2025-04-30,"1,263.05","2,228.77","2,228.77",965.72,2,14058,PREM40,dmd,2.00,gdl
708014,761092,gdl 455104,2025-04-30,394.35,700.14,700.14,305.78,3,14058,PREM6,dmd,2.00,gdl
708015,761093,gdl 455104,2025-04-30,"4,053.54","7,036.39","7,036.39","2,982.85",6,14058,PUP40,dmd,2.00,gdl
708016,761094,gdl 455104,2025-04-30,"1,671.42","2,975.59","2,975.59","1,304.16",4,14058,SAL15,nat,2.00,gdl

In [41]:
routes = pd.read_csv('../data/routes.csv')
display(routes)

,route_number,route_name,commission_type,commission,notes,type_id,channel_id,warehouse_id
0,157,luis vallarta,f,"10,000.00",NaN,4,2,gdl
1,24,lorena colunga,v,0.00,NaN,4,2,snc
2,13,gerente puebla,v,0.00,ac,4,2,pue
3,3,vacante,v,0.00,NaN,4,2,snc
4,122,abraham,f,"10,000.00",ac,4,2,cdmx1
...,...,...,...,...,...,...,...,...
120,107,jorge,v,0.00,NaN,4,2,snc
121,110,perla,v,0.00,NaN,4,2,snc
122,100,gerente queretaro,v,0.00,NaN,4,2,snc
123,90,agente ecomerce,v,0.00,NaN,4,1,ecm
124,144,vacante,v,0.00,ac,4,2,pue

In [42]:
customers = pd.read_csv('../data/customers.csv')
display(customers)

,code,name,registration_date,credit_limit,credit_days,customer_type_id,opinion_leader
0,10420,leticia govea vazquez,2006-12-29,"10,000.00",15,8,False
1,10531,miguel angel dominguez galvez,2006-12-29,"10,000.00",15,5,False
2,10854,rodolfo gomez ortiz,2006-12-29,"10,000.00",30,5,False
3,10858,maria adela gutierrez salcido,2006-12-29,"60,000.00",30,8,False
4,10056,daniela alton zepeda,2006-12-29,"30,000.00",30,5,False
...,...,...,...,...,...,...,...
9118,93438,martha gabriela morales gomez,2026-03-18,"10,000.00",7,8,False
9119,93439,rosa isela sosa vazquez,2026-03-18,"10,000.00",7,8,False
9120,93440,erick rodriguez dominguez,2026-03-18,"10,000.00",7,5,False
9121,93464,victor manuel ramos gonzalez,2026-04-29,"10,000.00",7,5,False
9122,93465,angel omar cruz ponce,2026-04-30,"10,000.00",7,8,False

### Promedio trimestral por cliente

In [43]:
print('sales columns')
print(sales.columns)

print('\nroutes columns')
print(routes.columns)

print('\ncustomers columns')
print(customers.columns)

sales columns
Index(['id', 'doc_id', 'sale_date', 'total_cost', 'net_price', 'gross_price',
       'profit', 'quantity', 'customer_id', 'product_id', 'product_class_id',
       'route_id', 'warehouse_id'],
      dtype='str')

routes columns
Index(['route_number', 'route_name', 'commission_type', 'commission', 'notes',
       'type_id', 'channel_id', 'warehouse_id'],
      dtype='str')

customers columns
Index(['code', 'name', 'registration_date', 'credit_limit', 'credit_days',
       'customer_type_id', 'opinion_leader'],
      dtype='str')

In [44]:
#definir rngo de fecha (trimestre movil pasado)
sales_lq = sales.copy()

sales_lq['sale_date'] = pd.to_datetime(sales_lq['sale_date'])

sales_lq = sales_lq[(sales_lq['sale_date'] >= '2026-02-01') & (sales_lq['sale_date'] <= '2026-04-30')]

sales_lq

,id,doc_id,sale_date,total_cost,net_price,gross_price,profit,quantity,customer_id,product_id,product_class_id,route_id,warehouse_id
15009,882059,gdl 481970,2026-02-25,"1,070.00","1,562.00","1,562.00",492.00,1,11962,ZO138,zts,41.00,gdl
15351,883850,gdl 479826,2026-02-03,"2,380.00","3,474.00","3,474.00","1,094.00",2,12592,ZO140,zts,2.00,gdl
15833,887725,col 47882,2026-02-19,298.00,448.00,448.00,150.00,2,14266,ZO133,zts,85.00,col
17290,887726,col 47882,2026-02-19,800.00,"1,200.00","1,200.00",400.00,5,14266,ZO134,zts,85.00,col
17359,888159,col 46893,2026-02-18,0.00,-87.84,0.00,-87.84,0,14389,219340,msd,81.00,col
...,...,...,...,...,...,...,...,...,...,...,...,...,...
423128,2288076,ln 64440,2026-04-23,495.57,"1,033.45","1,033.45",537.88,1,50832,INDCAT18,nat,7.00,leo
423129,2288077,ln 64510,2026-04-27,680.68,"1,578.88","1,578.88",898.20,1,50832,SKIN25,care,7.00,leo
423130,2288078,ln 64618,2026-04-30,546.27,"1,055.46","1,055.46",509.18,1,50832,MAN40,dmd,7.00,leo
423131,2288079,ln 64666,2026-04-30,39.12,90.43,90.43,51.32,1,50836,MANC1,dmd,68.00,leo
700049,881847,gdl 480349,2026-02-16,0.00,-233.27,0.00,-233.27,0,11864,EX40,nat,41.00,gdl

In [45]:
# merge con rutas y clientes para tener toda la info en un solo df
sales_lq = sales_lq.merge(routes[['route_number', 'route_name', 'warehouse_id']], left_on='route_id', right_on='route_number', how='left')

sales_lq = sales_lq.merge(customers[['code', 'name', 'registration_date']], left_on='customer_id', right_on='code', how='left')

sales_lq.columns

Index(['id', 'doc_id', 'sale_date', 'total_cost', 'net_price', 'gross_price',
       'profit', 'quantity', 'customer_id', 'product_id', 'product_class_id',
       'route_id', 'warehouse_id_x', 'route_number', 'route_name',
       'warehouse_id_y', 'code', 'name', 'registration_date'],
      dtype='str')

In [46]:
sales_lq = sales_lq[['sale_date','route_number', 'route_name',
                     'warehouse_id_y', 'customer_id', 'name',
                     'registration_date', 'product_id', 'product_class_id', 'quantity', 'profit', 'total_cost', 'net_price', 'gross_price']]

sales_lq

,sale_date,route_number,route_name,warehouse_id_y,customer_id,name,registration_date,product_id,product_class_id,quantity,profit,total_cost,net_price,gross_price
0,2026-02-25,41,katia gastelum,gdl,11962,ana cecilia garcia jimenez,2011-12-20,ZO138,zts,1,492.00,"1,070.00","1,562.00","1,562.00"
1,2026-02-03,2,abraham garcia,gdl,12592,ceinvej,2016-11-02,ZO140,zts,2,"1,094.00","2,380.00","3,474.00","3,474.00"
2,2026-02-19,85,armando,col,14266,alejandro garcia guevara,2024-03-06,ZO133,zts,2,150.00,298.00,448.00,448.00
3,2026-02-19,85,armando,col,14266,alejandro garcia guevara,2024-03-06,ZO134,zts,5,400.00,800.00,"1,200.00","1,200.00"
4,2026-02-18,81,melissa,col,14389,monserrat araceli ibarra delgadillo,2024-12-11,219340,msd,0,-87.84,0.00,-87.84,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80196,2026-04-23,7,bodega leon,leo,50832,juan pablo duran segura,2025-08-14,INDCAT18,nat,1,537.88,495.57,"1,033.45","1,033.45"
80197,2026-04-27,7,bodega leon,leo,50832,juan pablo duran segura,2025-08-14,SKIN25,care,1,898.20,680.68,"1,578.88","1,578.88"
80198,2026-04-30,7,bodega leon,leo,50832,juan pablo duran segura,2025-08-14,MAN40,dmd,1,509.18,546.27,"1,055.46","1,055.46"
80199,2026-04-30,68,elena manriquez,leo,50836,croquetas san juditas,2025-10-17,MANC1,dmd,1,51.32,39.12,90.43,90.43
80200,2026-02-16,41,katia gastelum,gdl,11864,teresa alanis de alba,2010-09-28,EX40,nat,0,-233.27,0.00,-233.27,0.00

In [47]:
#agrupacion por mes > ruta > cliente

sales_lq_agg_month_rt_ctm = sales_lq.copy()

#obtencion del mes
sales_lq_agg_month_rt_ctm['sale_month'] = sales_lq_agg_month_rt_ctm['sale_date'].dt.to_period('M')

sales_lq_agg_month_rt_ctm = (sales_lq_agg_month_rt_ctm
                             .groupby(['sale_month', 'route_number', 'customer_id'], as_index=False)
                             .agg({
                                 'product_id': 'nunique',
                                 'product_class_id': 'nunique',
                                 'quantity': 'sum',
                                 'profit': 'sum',
                                 'total_cost': 'sum',
                                 'net_price': 'sum',
                                 'gross_price': 'sum'
                             }))

sales_lq_agg_month_rt_ctm

,sale_month,route_number,customer_id,product_id,product_class_id,quantity,profit,total_cost,net_price,gross_price
0,2026-02,1,10451,4,1,7,702.49,589.85,"1,292.34","1,292.34"
1,2026-02,1,10828,1,1,1,92.93,65.08,158.02,158.02
2,2026-02,1,11009,1,1,1,540.71,548.44,"1,089.14","1,089.14"
3,2026-02,1,11424,1,1,1,497.44,505.00,"1,002.44","1,002.44"
4,2026-02,1,11442,5,1,24,"1,535.98","1,646.33","3,182.31","3,251.30"
...,...,...,...,...,...,...,...,...,...,...
7107,2026-04,157,70159,2,1,3,604.41,571.80,"1,176.21","1,176.21"
7108,2026-04,157,70160,1,1,50,"-7,864.83","10,214.83","2,350.00","2,500.00"
7109,2026-04,157,70161,9,2,31,"5,913.10","5,203.45","11,116.55","12,932.07"
7110,2026-04,157,70163,1,1,20,762.06,"1,937.21","2,699.27","2,699.27"
7111,2026-04,157,70164,4,1,8,554.87,702.04,"1,256.91","1,256.91"

In [48]:
sales_lq_agg_month_rt_ctm = (sales_lq_agg_month_rt_ctm
                             .merge(customers[['code', 'name', 'registration_date']],
                                    left_on='customer_id', right_on='code', how='left')
                            .merge(routes[['route_number', 'route_name', 'warehouse_id']],
                                   left_on='route_number', right_on='route_number', how='left'))

sales_lq_agg_month_rt_ctm = sales_lq_agg_month_rt_ctm[[ 'sale_month', 'route_number','route_name', 'warehouse_id', 'customer_id','name', 'registration_date', 'product_id', 'product_class_id', 'quantity', 'profit', 'total_cost', 'net_price', 'gross_price' ]]

sales_lq_agg_month_rt_ctm

,sale_month,route_number,route_name,warehouse_id,customer_id,name,registration_date,product_id,product_class_id,quantity,profit,total_cost,net_price,gross_price
0,2026-02,1,bodega guadalajara,gdl,10451,miguel angel cerda preciado,2006-12-29,4,1,7,702.49,589.85,"1,292.34","1,292.34"
1,2026-02,1,bodega guadalajara,gdl,10828,eduardo carvajal ulloa,2006-12-29,1,1,1,92.93,65.08,158.02,158.02
2,2026-02,1,bodega guadalajara,gdl,11009,alejandro ibarra gonzalez,2007-03-08,1,1,1,540.71,548.44,"1,089.14","1,089.14"
3,2026-02,1,bodega guadalajara,gdl,11424,manuel maldonado ramirez,2006-12-29,1,1,1,497.44,505.00,"1,002.44","1,002.44"
4,2026-02,1,bodega guadalajara,gdl,11442,mauricio jose morales aguilar,2006-12-29,5,1,24,"1,535.98","1,646.33","3,182.31","3,251.30"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7107,2026-04,157,luis vallarta,gdl,70159,jesus antonio torres estrada,2026-04-21,2,1,3,604.41,571.80,"1,176.21","1,176.21"
7108,2026-04,157,luis vallarta,gdl,70160,arcelia monserrat de la cerda villar,2026-04-22,1,1,50,"-7,864.83","10,214.83","2,350.00","2,500.00"
7109,2026-04,157,luis vallarta,gdl,70161,maria isabel arzate torres,2026-04-22,9,2,31,"5,913.10","5,203.45","11,116.55","12,932.07"
7110,2026-04,157,luis vallarta,gdl,70163,marianna medina arzate,2026-04-28,1,1,20,762.06,"1,937.21","2,699.27","2,699.27"
7111,2026-04,157,luis vallarta,gdl,70164,alina quiroz hernandez,2026-04-30,4,1,8,554.87,702.04,"1,256.91","1,256.91"

In [49]:
#calculo de promedio en base a la fecha de registro

#promedio mensual por cliente

def calculate_monthly_average(row, *,
                              base_divisor: int = 3,
                              registration_date_column: str = 'registration_date',
                              calculation_column: str = 'net_price',
                              start_from: str = None,
                              end_to: str = None
                              ) -> float:
    
    """
    Calculates the monthly average of a specified calculation column based on the registration date column.
    The average is calculated by dividing the sum of the calculation column by the base divisor for each month.
    in case the registration date is less than the base divisor, the divisor will be the number of months since registration.

    This is a function to be applied by row in a DataFrame, where the registration date column contains the date of registration for each client,
    and the calculation column contains the values to be averaged.

    params:
    -------
    base_divisor: int
        The number of months to use as the divisor for the average calculation. Default is 3.
    registration_date_column: str
        The name of the column that contains the registration date. Default is 'sale_month'.
    calculation_column: str
        The name of the column that contains the values to be averaged. Default is 'net_price'.
    start_from: str
        The start date for the average calculation in 'YYYY-MM-DD' format. Default is None
    end_to: str
        The end date for the average calculation in 'YYYY-MM-DD' format. Default is None

    returns:
    -------
    pd.DataFrame
        A DataFrame containing the monthly averages for each client.
    """

    reg_date = pd.to_datetime(row[registration_date_column])
    start_date = pd.to_datetime(start_from)
    end_date = pd.to_datetime(end_to)

    if reg_date <= start_date:
        divisor = base_divisor

    elif reg_date > end_date:
        divisor = 1

    else:
        months_remaining = (end_date.year - reg_date.year) * 12 + (end_date.month - reg_date.month) + 1
        
        divisor = min(base_divisor, months_remaining)
        
    divisor = max(1, divisor)

    return row[calculation_column] / divisor

In [50]:
sales_lq_rt_ctm = sales_lq.copy()

sales_lq_rt_ctm = (sales_lq_rt_ctm
                             .groupby(['route_number', 'customer_id'], as_index=False)
                             .agg({
                                 'product_id': 'nunique',
                                 'product_class_id': 'nunique',
                                 'quantity': 'sum',
                                 'profit': 'sum',
                                 'total_cost': 'sum',
                                 'net_price': 'sum',
                                 'gross_price': 'sum'
                             }))

sales_lq_rt_ctm = (sales_lq_rt_ctm
                             .merge(customers[['code', 'name', 'registration_date']],
                                    left_on='customer_id', right_on='code', how='left')
                            .merge(routes[['route_number', 'route_name', 'warehouse_id']],
                                   left_on='route_number', right_on='route_number', how='left'))

sales_lq_rt_ctm = sales_lq_rt_ctm[['route_number','route_name', 'warehouse_id', 'customer_id','name', 'registration_date', 'product_id', 'product_class_id', 'quantity', 'profit', 'total_cost', 'net_price', 'gross_price' ]]

print(sales_lq['sale_date'].min(), sales_lq['sale_date'].max())
sales_lq_rt_ctm

2026-02-01 00:00:00 2026-04-30 00:00:00

,route_number,route_name,warehouse_id,customer_id,name,registration_date,product_id,product_class_id,quantity,profit,total_cost,net_price,gross_price
0,1,bodega guadalajara,gdl,10451,miguel angel cerda preciado,2006-12-29,4,1,12,"1,330.77","1,108.01","2,438.78","2,474.75"
1,1,bodega guadalajara,gdl,10483,adrian nicolas cruz fuentes,2006-12-29,2,1,3,"1,781.01","1,786.72","3,567.72","3,567.72"
2,1,bodega guadalajara,gdl,10524,gabriel diaz romero,2006-12-29,1,1,1,448.16,417.90,866.06,866.06
3,1,bodega guadalajara,gdl,10828,eduardo carvajal ulloa,2006-12-29,1,1,2,180.27,129.44,309.71,309.71
4,1,bodega guadalajara,gdl,11009,alejandro ibarra gonzalez,2007-03-08,1,1,1,540.71,548.44,"1,089.14","1,089.14"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3098,157,luis vallarta,gdl,70159,jesus antonio torres estrada,2026-04-21,2,1,3,604.41,571.80,"1,176.21","1,176.21"
3099,157,luis vallarta,gdl,70160,arcelia monserrat de la cerda villar,2026-04-22,1,1,50,"-7,864.83","10,214.83","2,350.00","2,500.00"
3100,157,luis vallarta,gdl,70161,maria isabel arzate torres,2026-04-22,9,2,31,"5,913.10","5,203.45","11,116.55","12,932.07"
3101,157,luis vallarta,gdl,70163,marianna medina arzate,2026-04-28,1,1,20,762.06,"1,937.21","2,699.27","2,699.27"
3102,157,luis vallarta,gdl,70164,alina quiroz hernandez,2026-04-30,4,1,8,554.87,702.04,"1,256.91","1,256.91"

In [51]:
sales_lq_rt_ctm['mean_net_price'] = sales_lq_rt_ctm.apply(calculate_monthly_average, axis=1, calculation_column='net_price', registration_date_column='registration_date', start_from='2026-02-01', end_to='2026-04-30')
sales_lq_rt_ctm['mean_gross_price'] = sales_lq_rt_ctm.apply(calculate_monthly_average, axis=1, calculation_column='gross_price', registration_date_column='registration_date', start_from='2026-02-01', end_to='2026-04-30')
sales_lq_rt_ctm['mean_profit'] = sales_lq_rt_ctm.apply(calculate_monthly_average, axis=1, calculation_column='profit', registration_date_column='registration_date', start_from='2026-02-01', end_to='2026-04-30')
sales_lq_rt_ctm['mean_total_cost'] = sales_lq_rt_ctm.apply(calculate_monthly_average, axis=1, calculation_column='total_cost', registration_date_column='registration_date', start_from='2026-02-01', end_to='2026-04-30')
sales_lq_rt_ctm['mean_quantity'] = sales_lq_rt_ctm.apply(calculate_monthly_average, axis=1, calculation_column='quantity', registration_date_column='registration_date', start_from='2026-02-01', end_to='2026-04-30')

sales_lq_rt_ctm

,route_number,route_name,warehouse_id,customer_id,name,registration_date,product_id,product_class_id,quantity,profit,total_cost,net_price,gross_price,mean_net_price,mean_gross_price,mean_profit,mean_total_cost,mean_quantity
0,1,bodega guadalajara,gdl,10451,miguel angel cerda preciado,2006-12-29,4,1,12,"1,330.77","1,108.01","2,438.78","2,474.75",812.93,824.92,443.59,369.34,4.00
1,1,bodega guadalajara,gdl,10483,adrian nicolas cruz fuentes,2006-12-29,2,1,3,"1,781.01","1,786.72","3,567.72","3,567.72","1,189.24","1,189.24",593.67,595.57,1.00
2,1,bodega guadalajara,gdl,10524,gabriel diaz romero,2006-12-29,1,1,1,448.16,417.90,866.06,866.06,288.69,288.69,149.39,139.30,0.33
3,1,bodega guadalajara,gdl,10828,eduardo carvajal ulloa,2006-12-29,1,1,2,180.27,129.44,309.71,309.71,103.24,103.24,60.09,43.15,0.67
4,1,bodega guadalajara,gdl,11009,alejandro ibarra gonzalez,2007-03-08,1,1,1,540.71,548.44,"1,089.14","1,089.14",363.05,363.05,180.24,182.81,0.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3098,157,luis vallarta,gdl,70159,jesus antonio torres estrada,2026-04-21,2,1,3,604.41,571.80,"1,176.21","1,176.21","1,176.21","1,176.21",604.41,571.80,3.00
3099,157,luis vallarta,gdl,70160,arcelia monserrat de la cerda villar,2026-04-22,1,1,50,"-7,864.83","10,214.83","2,350.00","2,500.00","2,350.00","2,500.00","-7,864.83","10,214.83",50.00
3100,157,luis vallarta,gdl,70161,maria isabel arzate torres,2026-04-22,9,2,31,"5,913.10","5,203.45","11,116.55","12,932.07","11,116.55","12,932.07","5,913.10","5,203.45",31.00
3101,157,luis vallarta,gdl,70163,marianna medina arzate,2026-04-28,1,1,20,762.06,"1,937.21","2,699.27","2,699.27","2,699.27","2,699.27",762.06,"1,937.21",20.00
3102,157,luis vallarta,gdl,70164,alina quiroz hernandez,2026-04-30,4,1,8,554.87,702.04,"1,256.91","1,256.91","1,256.91","1,256.91",554.87,702.04,8.00

In [52]:
#verificacion de rutas
df_filtered = sales_lq_rt_ctm[sales_lq_rt_ctm['route_number'] == 120].sort_values('mean_net_price', ascending=False)
df_filtered

,route_number,route_name,warehouse_id,customer_id,name,registration_date,product_id,product_class_id,quantity,profit,total_cost,net_price,gross_price,mean_net_price,mean_gross_price,mean_profit,mean_total_cost,mean_quantity
1758,120,arturo,cdmx,92604,macro distribuidora medivet,2025-01-29,50,1,10622,"396,412.53","1,197,209.62","1,593,622.15","1,660,037.82","531,207.38","553,345.94","132,137.51","399,069.87","3,540.67"
1752,120,arturo,cdmx,90727,productos veterinarios del valle de mexico,2024-09-19,38,1,6711,"192,827.44","568,264.44","761,091.88","762,092.10","253,697.29","254,030.70","64,275.81","189,421.48","2,237.00"
1755,120,arturo,cdmx,90801,petvet,2025-01-08,40,2,3759,"227,195.04","503,263.07","730,458.12","775,872.43","243,486.04","258,624.14","75,731.68","167,754.36","1,253.00"
1763,120,arturo,cdmx,93248,fynsa,2025-06-27,37,1,2747,"117,065.52","405,388.42","522,453.94","523,638.22","174,151.31","174,546.07","39,021.84","135,129.47",915.67
1753,120,arturo,cdmx,90734,marlovet,2024-10-09,3,1,1000,"106,961.90","182,235.10","289,197.00","289,197.00","96,399.00","96,399.00","35,653.97","60,745.03",333.33
1751,120,arturo,cdmx,90718,grupo veterinario cardona,2024-08-12,39,5,1043,"117,041.04","149,280.44","266,321.48","282,137.92","88,773.83","94,045.97","39,013.68","49,760.15",347.67
1756,120,arturo,cdmx,91045,centro integral de atencion para la mascota co...,2024-08-16,32,3,735,"48,770.38","156,238.11","205,008.49","208,146.63","68,336.16","69,382.21","16,256.79","52,079.37",245.00
1759,120,arturo,cdmx,93009,pablo claudio ramirez,2025-01-29,18,1,2234,"39,486.75","158,058.81","197,545.56","207,333.01","65,848.52","69,111.00","13,162.25","52,686.27",744.67
1764,120,arturo,cdmx,93272,vetfarma,2025-07-21,32,3,589,"64,764.07","127,217.94","191,982.02","214,175.41","63,994.01","71,391.80","21,588.02","42,405.98",196.33
1765,120,arturo,cdmx,93286,distribuidora animalitos pharma,2025-08-07,19,1,816,"24,791.74","65,876.87","90,668.61","90,668.61","30,222.87","30,222.87","8,263.91","21,958.96",272.00
1762,120,arturo,cdmx,93167,antonio flores mata,2025-04-29,20,1,557,"17,140.03","42,937.01","60,077.04","66,031.86","20,025.68","22,010.62","5,713.34","14,312.34",185.67
1747,120,arturo,cdmx,21045,comercializadora vetline,2020-01-20,52,5,496,"2,057.31","55,059.88","57,117.18","75,606.88","19,039.06","25,202.29",685.77,"18,353.29",165.33
1760,120,arturo,cdmx,93050,mascotas mr. spanky,2025-02-19,27,5,126,"18,066.45","31,155.94","49,222.38","49,222.38","16,407.46","16,407.46","6,022.15","10,385.31",42.00
1748,120,arturo,cdmx,90492,carbono comsolta,2023-04-19,22,2,242,"9,990.88","26,677.44","36,668.32","36,668.32","12,222.77","12,222.77","3,330.29","8,892.48",80.67
1750,120,arturo,cdmx,90704,comercializadora de productos veterinarios delta,2024-07-11,9,2,90,"8,469.05","22,954.06","31,423.11","31,423.11","10,474.37","10,474.37","2,823.02","7,651.35",30.00
1766,120,arturo,cdmx,93340,central zoo,2025-10-02,10,1,108,"9,685.81","21,461.49","31,147.30","35,277.43","10,382.43","11,759.14","3,228.60","7,153.83",36.00
1761,120,arturo,cdmx,93148,abastecedora veterinaria dajo pets,2025-04-08,7,2,108,"2,809.39","15,857.93","18,667.32","18,667.32","6,222.44","6,222.44",936.46,"5,285.98",36.00
1754,120,arturo,cdmx,90742,jorge mauricio varela razo,2024-11-11,4,1,12,"2,990.71","2,768.32","5,759.03","5,759.03","1,919.68","1,919.68",996.90,922.77,4.00
1757,120,arturo,cdmx,91412,centro veterinario cima,2024-04-16,4,1,29,"1,293.60","1,989.49","3,283.09","3,283.09","1,094.36","1,094.36",431.20,663.16,9.67
1749,120,arturo,cdmx,90662,banfield international de mexico,2024-04-23,1,1,4,972.12,"1,805.40","2,777.52","2,777.52",925.84,925.84,324.04,601.80,1.33

In [53]:
def gini(x):
    x = np.array(x, dtype=np.float64)
    x = x[x > 0]
    
    if len(x) == 0 or np.mean(x) == 0:
        return 0.0
        
    mad = np.abs(np.subtract.outer(x, x)).mean()
    rmad = mad / np.mean(x)
    g = 0.5 * rmad
    return g

In [54]:
list_routes = routes[routes['warehouse_id'].isin(['gdl', 'cdmx', 'cdmx1', 'cdmx2'])]['route_number'].unique().tolist()

metrics = []

for route in list_routes:
    df_route = sales_lq_rt_ctm[sales_lq_rt_ctm['route_number'] == route]

    if df_route.empty:
        print(f'Route: {route} - no data for this period.')
        continue

    net_price_arr = df_route['mean_net_price']

    #inidice de gini
    gini_val = gini(net_price_arr)

    median_price = np.median(net_price_arr)
    mean_price = np.mean(net_price_arr)

    if median_price != 0:
        diff_pct_median = ((mean_price - median_price) / abs(mean_price)) * 100
    else:
        diff_pct_median = 0.0

    metrics.append({
        'ruta': route,
        'Clientes con compras': len(net_price_arr),
        'Gini': gini_val * 100,
        'Media de venta neta': mean_price,
        'Mediana de venta neta': median_price,
        'Diferencia porcentual mediana > media': diff_pct_median
    })

metrics_routes_df = pd.DataFrame(metrics)

In [55]:
pd.options.display.float_format = '{:,.2f}'.format
metrics_routes_df

,ruta,Clientes con compras,Gini,Media de venta neta,Mediana de venta neta,Diferencia porcentual mediana > media
0,157,21,56.08,"6,715.70","2,801.91",58.28
1,122,69,70.25,"7,489.85","2,499.72",66.63
2,126,74,59.57,"4,825.44","2,610.20",45.91
3,127,68,55.13,"4,525.99","2,487.73",45.03
4,129,58,55.37,"9,850.09","5,592.82",43.22
5,130,65,64.53,"4,178.49","1,836.42",56.05
6,101,67,51.70,"6,173.72","3,772.01",38.90
7,128,64,68.63,"5,801.96","2,276.57",60.76
8,97,61,59.60,"5,015.98","2,594.81",48.27
9,120,20,65.93,"85,741.53","25,124.27",70.70
10,136,93,57.39,"2,155.09","1,237.25",42.59
11,142,81,44.39,"1,562.82","1,138.11",27.18
12,53,41,52.25,"6,018.10","3,211.21",46.64
13,1,98,84.29,"5,320.79",999.57,81.21
14,121,86,46.10,"2,392.18","1,493.63",37.56
15,153,74,56.59,"2,586.78","1,429.51",44.74
16,2,45,73.00,"27,994.55","7,482.88",73.27
17,26,61,56.45,"35,951.13","19,424.56",45.97
18,41,89,55.20,"7,057.88","4,039.95",42.76
19,55,77,58.05,"9,941.60","5,072.86",48.97
20,64,78,61.79,"19,140.32","7,663.01",59.96
21,59,88,62.70,"10,271.72","4,443.45",56.74
22,124,69,55.51,"3,657.78","2,067.37",43.48
23,125,71,57.88,"4,297.89","1,807.23",57.95
24,103,79,55.12,"3,681.34","1,947.43",47.10
25,105,64,59.97,"4,675.92","2,210.68",52.72
26,94,89,68.26,"7,374.30","3,081.07",58.22
27,123,12,55.45,"69,406.45","37,220.38",46.37
28,146,6,70.33,"15,140.82","3,418.72",77.42
29,92,14,66.75,"141,155.61","63,211.35",55.22
30,96,10,71.89,"140,408.62","24,692.12",82.41
31,145,22,82.73,"18,932.36","2,254.54",88.09

In [56]:
#umbrales de evaluacion sana
gini_threshold = metrics_routes_df['Gini'].median()
gini_threshold

np.float64(58.80958784995454)